# Test EC2
---
- name: Create Instance
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Include the variables for Test EC2
      include_vars: group_vars/test

    - name: Launch EC2 instance for Test EC2
      ec2:
        assign_public_ip: yes
        image: "{{ ec2_image }}"
        instance_tags:
           tag_id: "{{ ec2_tag }}"
           Name: "{{ ec2_name }}"
        exact_count: "{{ ec2_exact_count }}"
        count_tag: "{{ ec2_name }}"
        instance_type: "{{ ec2_instance_type }}"
        key_name: "{{ ec2_key_name }}"
        region: "{{ ec2_region }}"
        vpc_subnet_id: "{{ ec2_vpc_subnet_id}}"
        group_id: "{{ ec2_group_id }}"
        wait: yes
        monitoring: yes
      register: ec2

    - name: Add new instance to host group
      sudo: yes
      add_host: hostname={{ item.private_ip }} groupname=test_ec2
      with_items: ec2.instances
      register: add_host

    - name: Associating Elastic IP with the new intance
      with_items: ec2.instances
      ec2_eip: instance_id={{ item.id }} ip={{ ec2_elastic_ip }} region={{ ec2_region }}

    - name: Wait for SSH to come up
      wait_for: host={{ item.private_ip }} port=22 delay=10 timeout=60 state=started
      with_items: ec2.instances

- name: Playbook for install base system
  gather_facts: False
  hosts: test_ec2

  roles:
    # Basic Roles
    - time_zone_ubuntu
    - common_ubuntu
    - pip_ubuntu
